# Generated by Django 5.1.6 on 2025-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="category",
            field=models.CharField(default="csharp", max_length=30),
        ),
    ]
