# Generated by Django 5.1.6 on 2025-03-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_page_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.CharField(default="", max_length=30),
        ),
    ]
