# Generated by Django 5.2.1 on 2025-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['category', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
